Python 3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # Day 3 - Elif, And, Or
... 
... marks = int(input("Enter marks: "))
... 
... if marks >= 90:
...     print("A")
... 
... elif marks >= 75:
...     print("B")
... 
... elif marks >= 40:
...     print("C")
... 
... else:
...     print("FAIL")
... 
... 
... age = int(input("Enter age: "))
... 
... if age >= 18 and age <= 60:
...     print("Eligible")
... 
... else:
