Python 3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # Day 4 - Loops
... 
... print("Numbers from 1 to 10")
... 
... for i in range(1, 11):
...     print(i)
... 
... print("\nMultiplication Table")
... 
... num = int(input("Enter number: "))
... 
... for i in range(1, 11):
...     print(num, "x", i, "=", num * i)
... 
... print("\nSum of N numbers")
... 
... n = int(input("Enter n: "))
... 
... total = 0
... 
... for i in range(1, n + 1):
...     total = total + i
... 
